name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build
      run: pwsh make.ps1
    - name: Package
      run: pwsh make.ps1 package
    - uses: actions/upload-artifact@v2
      with:
        name: packages
        path: Package/Release/Packages
    - name: Test (net48)
      run: ./make.ps1 -frameworks net48 test-all
      shell: pwsh
    - name: Test (net6.0)
      run: ./make.ps1 -frameworks net6.0 test-all
      shell: pwsh
